config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.ht
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end
# resources :doses, only: [:show]
#   delete 'doses/:id', to: 'doses#destroy'
# resources :cocktails, except: [:index]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id, message: "This igredient already exists!" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  # has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])

  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail.id)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.delete
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def show
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail)
  end

private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="edit-page">
  <div class="container">
    <div>
      <h1 class="text-center"> Edit - <%= @cocktail.name %></h1>
      <div class="edit-grid">
        <div class="ingredients-edit">
          <% @cocktail.doses.each do |dose| %>
            <p><%= dose.description%><%= dose.ingredient.name %><%= link_to " | delete ", dose_path(dose), method: :delete %><i class="far fa-trash-alt"></i></p>
          <% end %>
        </div>
        <div class="form">
          <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name, input_html: { class: 'input' }%>
            <label class="btn submit">
            Add a photo
            <span style="display:none;">
            <%= f.input :photo, as: :file %>
            </span>
            </label> <br>
          <%= f.button :submit, input_html: { class: 'submit' } %>
          <% end %>
        </div>
      </div>
    </div>
  <%= link_to '⬅ Back To Cocktail', cocktail_path(@cocktail), class: "btn-back" %>
  </div>
</div>

app/views/cocktails/index.html.erb
<%= content_for(:navbar_class, "navbar-home") %>

<div class="banner">
  <div class="container">
    <h1>Create your own cocktail </h1>
    <p>Keep your favourite recipes in one place </p>
    <%= link_to "New Cocktail", new_cocktail_path, class: "btn-banner" %>
  </div>
</div>

<div class="cocktails-wrapper">
  <div class="d-flex flex-wrap cocktail-cards">
    <% @cocktails.each do |cocktail| %>
      <div class="card m-3 d-flex">
        <% if cocktail.photo.attached? %>
          <%= cl_image_tag cocktail.photo.key, class: 'card-img-top card-image' %>
        <% end %>
        <div class="card-body">
          <h1 class="card-title"><%= cocktail.name %></h1>
          <%= link_to 'recipe', cocktail_path(cocktail), class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">Create a new cocktail!</h1>
</div>
<%= render 'shared/form' %>

app/views/cocktails/show.html.erb
<div class="cocktail-page">
  <h1 class="text-center"><%= @cocktail.name %></h1>
  <hr>
  <div class="cocktail-box container">
    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key %>
    <% else %>
     <%= image_tag ("cocktails.jpg") %>
    <% end %>
      <div class="ingredient-box">
        <h2>Ingredients:</h2>
        <div class="ingredients">
          <% @cocktail.doses.each do |dose| %>
            <p><%= dose.description%> <%= dose.ingredient.name %></p>
          <% end %>
        </div>
      </div>

    <div class="show-links">
      <%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail.id), class: 'btn' %>
      <%= link_to 'Edit Cocktail', edit_cocktail_path(@cocktail.id), class: 'btn' %>
      <%= link_to 'Delete Cocktail', cocktail_path(@cocktail.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn delete-btn' %>
    </div>
  </div>
</div>



<!-- div class="container">
   <% if @cocktail.photo.attached? %>
  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
  <% else %>
  <p>No image attached</p>
  <% end %>
  <h2> <%= "#{@cocktail.name}" %></h2>
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li><%= dose.description%> <%= dose.ingredient.name %><small><%= link_to ":x:", dose_path(dose), method: :delete %></small></li>
    <% end %>
  </ul>
  <br><br><br>
  <button type="button" class="btn btn-light" style="padding: 20px 50px; color: black;"><span> <%= link_to "Add doses", new_cocktail_dose_path(@cocktail) %> </span></button><br> <br>
  <button type="button" class="btn btn-light" style="padding: 20px 50px; color: black;"><span> <%= link_to "Back to Cocktails", "/cocktails" %> </span> </button>
</div> -->
<!-- <div class="cocktail-container">
  <h1 class="cocktail-name text-center mb-5"><%= @cocktail.name %></h1>
  <div class="cocktail-details">
    <ul>
      <h5 class="cocktail-doses">Ingredients</h5>
      <% @cocktail.doses.each do |dose| %>
        <li class="cocktail-doses"><%= dose.description %> - <%= dose.ingredient.name %></li>
      <% end %>
    </ul>
    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key, height: 400, width:400, crop: :fill, class: 'show-image' %>
    <% end %>
  </div>

</div> -->

app/views/doses/new.html.erb
<h1>Add new dose for<%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Grand+Hotel&family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 ">
      <div class="form">
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name, input_html: { class: 'input' }%>
          <label class="btn submit">
            Add a photo
            <span style="display:none;">
              <%= f.input :photo, as: :file %>
            </span>
          </label> <br>
          <%= f.button :submit, input_html: { class: 'submit' } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-retro_cocktails <%= yield(:navbar_class) %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("logo.png") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Cocktail menu", cocktails_path, class: "nav-link my-2 p-1", id: "navbar-text" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktail", new_cocktail_path, class: "nav-link my-2 p-1", id: "navbar-text"%>
      </li>
    </ul>
  </div>
</div>